# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Add Labels

on:
  pull_request:
    branches: [ master ]

jobs:
  Labels:
    env:
     Github : ${{ secrets.Github }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Check PR title
      uses: ./
 
