# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ADD LABELS

on:
  pull_request:
    branches: [ master ]

jobs:
  labeler:
    runs-on: [ubuntu-latest]
    env:
     Github : ${{ secrets.Github }}

    steps:
    - name: Check PR title
      uses: ./
 
